#!/usr/bin/env bash
# master/setup.sh — regenerate the (gitignored) master Synapse config from
# TRACKED, non-secret settings so a fresh master stack is reproducible.
#
# The secret-bearing homeserver.yaml is deliberately NOT tracked (it embeds the
# signing key path + registration_shared_secret + DB password). This script is
# the tracked source of every NON-secret setting — crucially the uplink-burst
# rate limits (rc_message / rc_invites / rc_room_creation) — and it MINTS the
# secrets locally, writing them only to gitignored 0600 files:
#
#   master/synapse/homeserver.yaml     rendered here (0600, gitignored)
#   master/synapse/master.signing.key  minted here if absent (0600, gitignored)
#   master/synapse/master.log.config   written here if absent (gitignored)
#   master/synapse/.secrets.local      the 3 shared secrets (0600, gitignored)
#   master/synapse/media_store/        created here, host-owned by UID 501 so the
#                                      Synapse container (UID 501) can write media
#
# The DB password is read from master/.env (MASTER_POSTGRES_PASSWORD) so Synapse
# and Postgres agree. Re-running is safe: existing secrets + signing key are
# reused, so an existing DB keeps working; only homeserver.yaml is re-rendered.
#
# Usage:
#   master/setup.sh                       # regenerate config
#   docker compose -p matrix-master --env-file master/.env \
#     -f master/docker-compose.master.yml up -d
#   master/provision.sh                   # create accounts + spaces
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH="/Applications/Docker.app/Contents/Resources/bin:${PATH}"

SYN_DIR="${HERE}/synapse"
HS_YAML="${SYN_DIR}/homeserver.yaml"
SIGNING_KEY="${SYN_DIR}/master.signing.key"
LOG_CONFIG="${SYN_DIR}/master.log.config"
SECRETS="${SYN_DIR}/.secrets.local"
MEDIA_DIR="${SYN_DIR}/media_store"
ENV_FILE="${HERE}/.env"
IMAGE='ghcr.io/element-hq/synapse:v1.159.0@sha256:edf259d2b575b669a3e81024918ab8d5cfb7d2fba5a53c9e09695f1abc5645cb'

log() { printf '[setup] %s\n' "$*" >&2; }
fail() { printf '[setup] ERROR: %s\n' "$*" >&2; exit 1; }

umask 077
mkdir -p "${SYN_DIR}" "${MEDIA_DIR}"

# --- DB password from .env (must match the Postgres container) ---
[ -f "${ENV_FILE}" ] || fail "missing ${ENV_FILE} (set MASTER_POSTGRES_PASSWORD)"
# shellcheck disable=SC1090
DB_PASSWORD="$(grep -E '^MASTER_POSTGRES_PASSWORD=' "${ENV_FILE}" | head -1 | cut -d= -f2-)"
[ -n "${DB_PASSWORD}" ] || fail "MASTER_POSTGRES_PASSWORD not set in ${ENV_FILE}"

gen_secret() { python3 -c 'import secrets;print(secrets.token_urlsafe(48))'; }

# --- three shared secrets: reuse if present, else mint + persist (0600) ---
if [ -s "${SECRETS}" ]; then
  # shellcheck disable=SC1090
  source "${SECRETS}"
  log "reusing existing shared secrets"
fi
MACAROON_SECRET="${MACAROON_SECRET:-$(gen_secret)}"
FORM_SECRET="${FORM_SECRET:-$(gen_secret)}"
REGISTRATION_SHARED_SECRET="${REGISTRATION_SHARED_SECRET:-$(gen_secret)}"
{
  echo "# matrix-master Synapse shared secrets (mode 600, gitignored). Do NOT commit."
  echo "MACAROON_SECRET='${MACAROON_SECRET}'"
  echo "FORM_SECRET='${FORM_SECRET}'"
  echo "REGISTRATION_SHARED_SECRET='${REGISTRATION_SHARED_SECRET}'"
} > "${SECRETS}"
chmod 600 "${SECRETS}"

# --- signing key: mint once via the Synapse image if absent ---
if [ ! -s "${SIGNING_KEY}" ]; then
  log "minting signing key ..."
  docker run --rm --entrypoint generate_signing_key "${IMAGE}" -o /dev/stdout \
    > "${SIGNING_KEY}" 2>/dev/null || fail "generate_signing_key failed"
  chmod 600 "${SIGNING_KEY}"
  log "wrote ${SIGNING_KEY}"
fi

# --- log config: static, write if absent ---
if [ ! -s "${LOG_CONFIG}" ]; then
  cat > "${LOG_CONFIG}" <<'LOGCFG'
version: 1
formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: precise
loggers:
    _placeholder:
        level: "INFO"
    synapse.storage.SQL:
        level: INFO
root:
    level: INFO
    handlers: [console]
disable_existing_loggers: false
LOGCFG
  log "wrote ${LOG_CONFIG}"
fi

# --- render homeserver.yaml (the tracked, non-secret settings live HERE) ---
cat > "${HS_YAML}" <<YAML
# GENERATED by master/setup.sh — do NOT edit by hand, do NOT commit.
# All NON-secret settings below are the tracked source of truth in setup.sh.
# Secrets (signing key, macaroon/form/registration) are minted locally.
#
# MASTER Synapse (server_name: master). CS API only, no federation, no public
# registration. Isolated from the live matrix-wa stack.
server_name: "master"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client]
        compress: false
database:
  name: psycopg2
  args:
    user: matrix
    password: "${DB_PASSWORD}"
    dbname: synapse
    host: postgres
    port: 5432
    cp_min: 5
    cp_max: 10
log_config: "/data/master.log.config"
media_store_path: /data/media_store
report_stats: false
macaroon_secret_key: "${MACAROON_SECRET}"
form_secret: "${FORM_SECRET}"
signing_key_path: "/data/master.signing.key"
trusted_key_servers: []

# No public registration. Provisioning uses the shared secret below with
# register_new_matrix_user against the local CS API (see master/provision.sh).
enable_registration: false
registration_shared_secret: "${REGISTRATION_SHARED_SECRET}"

# Federation stays off.
federation_domain_whitelist: []

rc_login:
  address:
    per_second: 0.15
    burst_count: 10
  account:
    per_second: 0.15
    burst_count: 10
  failed_attempts:
    per_second: 0.15
    burst_count: 10

rc_joins:
  local:
    per_second: 20
    burst_count: 300

# A teammate's first share creates many mirror rooms at once, and each
# createRoom emits several events. The default rc_message burst of 10 would 429
# the uplink partway through a burst of room creations / backfills. Loosen the
# message + invite limiters so the master can accept a real uplink's reconcile
# burst. (Master stack only — unrelated to the live matrix-wa hub.)
rc_message:
  per_second: 100
  burst_count: 1000
# createRoom is gated by its OWN limiter (rc_room_creation), NOT rc_message — the
# default (burst ~10, slow refill) 429s the uplink when a reconcile creates
# several mirror rooms plus the per-teammate proposals room in one window.
rc_room_creation:
  per_second: 10
  burst_count: 200
rc_invites:
  per_room:
    per_second: 100
    burst_count: 1000
  per_user:
    per_second: 100
    burst_count: 1000

# vim:ft=yaml
YAML
chmod 600 "${HS_YAML}"
log "wrote ${HS_YAML} (mode 600) with uplink-burst rate limits"
log "done. Next: bring the stack up, then run master/provision.sh"
